"""Shared data models - re-exports all model classes for convenient imports."""
# Architect models
from src.shared.models.architect import (
    DecomposeRequest,
    DecompositionResult,
    DecompositionRun,
    DomainEntity,
    DomainModel,
    DomainRelationship,
    EntityField,
    RelationshipType,
    ServiceDefinition,
    ServiceMap,
    ServiceStack,
    StateMachine,
    StateTransition,
)

# Contract models
from src.shared.models.contracts import (
    AsyncAPIContract,
    BreakingChange,
    ChannelSpec,
    ComplianceResult,
    ComplianceViolation,
    ContractCreate,
    ContractEntry,
    ContractListResponse,
    ContractStatus,
    ContractTestSuite,
    ContractType,
    ContractVersion,
    EndpointSpec,
    ImplementationRecord,
    ImplementationStatus,
    MarkRequest,
    MarkResponse,
    MessageSpec,
    OpenAPIContract,
    OperationSpec,
    SharedSchema,
    UnimplementedContract,
    ValidateRequest,
    ValidationResult,
)

# Codebase intelligence models
from src.shared.models.codebase import (
    CodeChunk,
    DeadCodeEntry,
    DependencyEdge,
    DependencyRelation,
    GraphAnalysis,
    ImportReference,
    IndexStats,
    Language,
    SemanticSearchResult,
    ServiceInterface,
    SymbolDefinition,
    SymbolKind,
)

# Common models
from src.shared.models.common import (
    ArtifactRegistration,
    BuildCycle,
    HealthStatus,
)

__all__ = [
    # Architect
    "ServiceStack",
    "RelationshipType",
    "ServiceDefinition",
    "EntityField",
    "StateTransition",
    "StateMachine",
    "DomainEntity",
    "DomainRelationship",
    "DomainModel",
    "ServiceMap",
    "DecompositionResult",
    "DecomposeRequest",
    "DecompositionRun",
    # Contracts
    "ContractType",
    "ContractStatus",
    "ImplementationStatus",
    "ContractEntry",
    "ContractCreate",
    "ContractListResponse",
    "EndpointSpec",
    "OpenAPIContract",
    "MessageSpec",
    "ChannelSpec",
    "OperationSpec",
    "AsyncAPIContract",
    "SharedSchema",
    "BreakingChange",
    "ContractVersion",
    "ImplementationRecord",
    "ValidationResult",
    "ValidateRequest",
    "MarkRequest",
    "MarkResponse",
    "UnimplementedContract",
    "ContractTestSuite",
    "ComplianceViolation",
    "ComplianceResult",
    # Codebase
    "SymbolKind",
    "Language",
    "DependencyRelation",
    "SymbolDefinition",
    "ImportReference",
    "DependencyEdge",
    "CodeChunk",
    "SemanticSearchResult",
    "ServiceInterface",
    "DeadCodeEntry",
    "GraphAnalysis",
    "IndexStats",
    # Common
    "BuildCycle",
    "ArtifactRegistration",
    "HealthStatus",
]
